spring:
  datasource:
    url: jdbc:sqlserver://diversityserver.database.windows.net:1433;database=diversitystorage;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: diversityuser
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9000

