
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#Swagger properties
app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.diversity.controller
    swagger:
      enable: true


###    url: jdbc:postgresql://us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io:5433/yugabyte?ssl=true&sslmode=verify-full&sslrootcert=C:\devl\wfb\hackathon\petclinic-spring-data-yugabytedb\.postgresql\root.crt

yugabyte:
  datasource:
    driver-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
    #host: 192.168.0.108
    host: us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io
    port: 5433
    db-name: hackathon
    username: user4
    password: user#4
    load-balance: true
    ssl-mode: disable
    #ssl-mode: verify-full
    #ssl-root-cert: C:/devl/wfb/hackathon/yugabyte-service/certs/root.crt
    connect-timeout: 60000
    socket-timeout: 60000
    login-timeout: 60000

management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"

# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte: DEBUG
  com.yugabyte.ysql.YBClusterAwareDataSource: TRACE
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE
