drop table TBL_DIV_LEADER IF EXISTS;
CREATE TABLE TBL_DIV_LEADER (
ID INT(5) NOT NULL,
NAME VARCHAR2(50)
COMPANY_NAME VARCHAR2(100),
MOBILE_NBR INT(10),
EMAIL_ID VARCHAR2(50),
GENDER VARCHAR2(1),
NATIONALITY VARCHAR2(25),
RELIGION VARCHAR2(50),
COLOR VARCHAR2(25),
LANG VARCHAR2(50),
MARITAL_ST VARCHAR2(50),
SEXUAL_ORIENT VARCHAR2(50),
POLITICAL_ORIENT VARCHAR2(50),
LGBT VARCHAR2(1),
VETERAN VARCHAR2(1),
DISABLED VARCHAR2(1),
SALARY INT(10),
)