drop table TBL_DIV_LEADER IF EXISTS;
CREATE TABLE TBL_DIV_LEADER (
ID INT(5) NOT NULL,
NAME VARCHAR2(50),
GENDER VARCHAR2(1),
ETHNICITY VARCHAR2(25),
LGBT VARCHAR2(1),
VETERAN VARCHAR2(1),
DISABLED VARCHAR2(1),
SHARE_PERCENT VARCHAR2(3)
)